package universidadc1g14.igu;

/**
 *
 * @author RAFAEL
 */
public class Inicio extends javax.swing.JFrame {

    
    /**
     * Creates new form Menu
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        salir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmiMateria = new javax.swing.JMenuItem();
        jmAlumno = new javax.swing.JMenu();
        jmiAlumno = new javax.swing.JMenuItem();
        jmInscripcion = new javax.swing.JMenu();
        jmiInscripcion = new javax.swing.JMenuItem();
        jmNotas = new javax.swing.JMenu();
        jmiNotas = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.orange);

        desktop.setBackground(new java.awt.Color(204, 204, 255));
        desktop.setDoubleBuffered(true);
        desktop.setRequestFocusEnabled(false);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        salir.setText("Archivo");

        jMenuItem1.setText("Salir del sistema");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        salir.add(jMenuItem1);

        jMenuBar1.add(salir);

        jmMateria.setText("Materias");

        jmiMateria.setText("Formulario Materias");
        jmiMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMateriaActionPerformed(evt);
            }
        });
        jmMateria.add(jmiMateria);

        jMenuBar1.add(jmMateria);

        jmAlumno.setText("Alumnos");

        jmiAlumno.setText("Formulario Alumnos");
        jmiAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiAlumno);

        jMenuBar1.add(jmAlumno);

        jmInscripcion.setText("Inscripciones");

        jmiInscripcion.setText("Formulario Inscripcion");
        jmiInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInscripcionActionPerformed(evt);
            }
        });
        jmInscripcion.add(jmiInscripcion);

        jMenuBar1.add(jmInscripcion);

        jmNotas.setText("Carga de notas");

        jmiNotas.setText("Formulario de Notas");
        jmiNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNotasActionPerformed(evt);
            }
        });
        jmNotas.add(jmiNotas);

        jMenuBar1.add(jmNotas);

        jmConsultas.setText("Consultas");
        jMenuBar1.add(jmConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        Inicio m1 = new Inicio();
        m1.setVisible(true);
        m1.setLocationRelativeTo(null);
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmiAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlumnoActionPerformed
        // TODO add your handling code here:
        desktop.removeAll();
        desktop.repaint();
        AlumnoView a = new AlumnoView();
        desktop.add(a);
        desktop.moveToFront(a);
    }//GEN-LAST:event_jmiAlumnoActionPerformed

    private void jmiMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMateriaActionPerformed
        // TODO add your handling code here:
        desktop.removeAll();
        desktop.repaint();
        MateriaView m = new MateriaView();
        desktop.add(m);
        desktop.moveToFront(m);
    }//GEN-LAST:event_jmiMateriaActionPerformed

    private void jmiInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInscripcionActionPerformed
        // TODO add your handling code here:
        desktop.removeAll();
        desktop.repaint();
        InscripcionView in = new InscripcionView();
        desktop.add(in);
        desktop.moveToFront(in);
    }//GEN-LAST:event_jmiInscripcionActionPerformed

    private void jmiNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNotasActionPerformed
        // TODO add your handling code here:
        desktop.removeAll();
        desktop.repaint();
        NotasView n = new NotasView();
        desktop.add(n);
        desktop.moveToFront(n);
    }//GEN-LAST:event_jmiNotasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenu jmInscripcion;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenu jmNotas;
    private javax.swing.JMenuItem jmiAlumno;
    private javax.swing.JMenuItem jmiInscripcion;
    private javax.swing.JMenuItem jmiMateria;
    private javax.swing.JMenuItem jmiNotas;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables
}
