package universidadc1g14.igu;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadc1g14.AccesoADatos.AlumnoData;
import universidadc1g14.AccesoADatos.Conexion;
import universidadc1g14.AccesoADatos.InscripcionData;
import universidadc1g14.AccesoADatos.MateriaData;
import universidadc1g14.Entidades.Alumno;
import universidadc1g14.Entidades.Inscripcion;
import universidadc1g14.Entidades.Materia;

/**
 *
 * @author RAFAEL
 */
public class InscripcionView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private ArrayList<Alumno> alumnos;
    private ArrayList<Materia> materias;
    private InscripcionData inscripcionData;
    private MateriaData materiaData;
    private AlumnoData alumnoData;
    private Conexion conexion;

    /**
     * Creates new form NuevoCliente
     */
    public InscripcionView() {
        initComponents();
        modelo = new DefaultTableModel();
        inscripcionData = new InscripcionData();
        materiaData = new MateriaData();
        materias = (ArrayList) materiaData.listarMaterias();
        alumnoData = new AlumnoData();
        alumnos = (ArrayList) alumnoData.listarAlumnos();
        cargarAlumnos();
        armarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        anular = new javax.swing.JButton();
        inscribir = new javax.swing.JButton();
        inscripta = new javax.swing.JRadioButton();
        noInscripta = new javax.swing.JRadioButton();
        cbAlumnos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMaterias = new javax.swing.JTable();

        setClosable(true);
        setForeground(java.awt.Color.orange);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Formulario de Inscripcion");
        setDoubleBuffered(true);
        setFocusTraversalPolicyProvider(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("[INSCRIPCION]");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ALUMNO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LISTADO DE MATERIAS");

        salir.setBackground(new java.awt.Color(204, 204, 255));
        salir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(0, 0, 204));
        salir.setText("Salir");
        salir.setContentAreaFilled(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        anular.setBackground(new java.awt.Color(204, 204, 255));
        anular.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        anular.setForeground(new java.awt.Color(0, 0, 204));
        anular.setText("Anular Inscripcion");
        anular.setContentAreaFilled(false);
        anular.setEnabled(false);
        anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anularActionPerformed(evt);
            }
        });

        inscribir.setBackground(new java.awt.Color(204, 204, 255));
        inscribir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        inscribir.setForeground(new java.awt.Color(0, 0, 204));
        inscribir.setText("Inscribir");
        inscribir.setContentAreaFilled(false);
        inscribir.setEnabled(false);
        inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscribirActionPerformed(evt);
            }
        });

        inscripta.setBackground(new java.awt.Color(204, 204, 255));
        inscripta.setForeground(new java.awt.Color(102, 153, 255));
        inscripta.setText("INSCRIPTAS");
        inscripta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscriptaActionPerformed(evt);
            }
        });

        noInscripta.setBackground(new java.awt.Color(204, 204, 255));
        noInscripta.setForeground(new java.awt.Color(102, 153, 255));
        noInscripta.setText("NO INSCRIPTAS");
        noInscripta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noInscriptaActionPerformed(evt);
            }
        });

        cbAlumnos.setBackground(new java.awt.Color(204, 204, 255));
        cbAlumnos.setForeground(new java.awt.Color(102, 153, 255));

        tMaterias.setBackground(new java.awt.Color(204, 204, 255));
        tMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tMaterias);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(anular, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inscripta)
                                .addGap(18, 18, 18)
                                .addComponent(noInscripta)
                                .addGap(169, 169, 169))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscripta)
                    .addComponent(noInscripta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscribir)
                    .addComponent(anular)
                    .addComponent(salir))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void anularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anularActionPerformed
        // TODO add your handling code here:
        Alumno alumnoSeleccionado = (Alumno) cbAlumnos.getSelectedItem();
        int filaSelec = tMaterias.getSelectedRow();
        if (filaSelec != -1) {
            int idM = (Integer) modelo.getValueAt(filaSelec, 0);

            inscripcionData.eliminarInscripcionMateria(alumnoSeleccionado.getIdAlumno(), idM );
            borrarTabla();

        } else {

            JOptionPane.showMessageDialog(this, "Usted debe seleccionar una materia");
        }


    }//GEN-LAST:event_anularActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dispose();

    }//GEN-LAST:event_salirActionPerformed

    private void inscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscribirActionPerformed
        // TODO add your handling code here:
        Alumno alumnoSeleccionado = (Alumno) cbAlumnos.getSelectedItem();
        int filaSelec = tMaterias.getSelectedRow();
        if (filaSelec != -1) {
            int idM = (Integer) modelo.getValueAt(filaSelec, 0);
            Materia mat = new Materia();
            mat.setIdMateria(idM);
            Inscripcion insc = new Inscripcion(0, alumnoSeleccionado, mat);
            inscripcionData.guardarInscripcion(insc);
            borrarTabla();

        } else {

            JOptionPane.showMessageDialog(this, "Usted debe seleccionar una materia");
        }


    }//GEN-LAST:event_inscribirActionPerformed

    private void inscriptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscriptaActionPerformed
        // TODO add your handling code here:
        inscripta.setSelected(true);
        noInscripta.setSelected(false);
        anular.setEnabled(true);
        inscribir.setEnabled(false);
        borrarTabla();
        llenarTabla();
    }//GEN-LAST:event_inscriptaActionPerformed

    private void noInscriptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noInscriptaActionPerformed
        // TODO add your handling code here:
        noInscripta.setSelected(true);
        inscripta.setSelected(false);
        anular.setEnabled(false);
        inscribir.setEnabled(true);
        borrarTabla();
        llenarTabla();
    }//GEN-LAST:event_noInscriptaActionPerformed

    private void borrarTabla() {
        int a = modelo.getRowCount() - 1;
        for (int i = a; i > 0; i--) {
            modelo.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anular;
    private javax.swing.JComboBox<Alumno> cbAlumnos;
    private javax.swing.JButton inscribir;
    private javax.swing.JRadioButton inscripta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton noInscripta;
    private javax.swing.JButton salir;
    private javax.swing.JTable tMaterias;
    // End of variables declaration//GEN-END:variables

    private void cargarAlumnos() {
        for (Alumno aux : alumnos) {
            cbAlumnos.addItem(aux);
        }
    }

    private void armarTabla() {
        ArrayList<Object> column = new ArrayList();
        column.add("Id");
        column.add("Nombre");
        column.add("Año");
        for (Object object : column) {
            modelo.addColumn(object);
        }
        tMaterias.setModel(modelo);
    }

    private void llenarTabla() {
        Alumno alumnoSeleccionado = (Alumno) cbAlumnos.getSelectedItem();

        if (noInscripta.isSelected()) {

            List<Materia> mat = inscripcionData.listarmateriasNoCursadas(alumnoSeleccionado.getIdAlumno());
            for (Materia m : mat) {

                modelo.addRow(new Object[]{m.getIdMateria(), m.getNombre(), m.getAnio()});
            }
        } else {
            List<Materia> mat = inscripcionData.listarmateriasCursadas(alumnoSeleccionado.getIdAlumno());
            for (Materia m : mat) {

                modelo.addRow(new Object[]{m.getIdMateria(), m.getNombre(), m.getAnio()});
            }

        }

    }

}
